pipeline {
    agent {
        docker {
            image 'maven:3.6.3-openjdk-11'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build ') {
            steps {
                sh 'mvn clean'
                sh 'mvn install'
            }
        }
         stage('Build Docker image ') {
            steps {
                app = docker.build("test")
            }
        }
    }
}